@ECHO OFF
CLS
ECHO. COMPILAR CFE - SISTEMA ERP - ESTOQUE-FINANCEIRO-FATRAMENTO-FISCAL
attrib cfe.exe -r
del cfe.exe

COPY 	..\SAG\SAG.CH
HBMake CFE.BC %1 > cfe-log.log
rem COPY CFE.EXE C:\CFEWEB\MAT2010
rem COPY CFE.EXE C:\CFEWEB\MAT2012
rem COPY CFE.EXE C:\CFEWEB\MAT2013
rem COPY CFE.EXE C:\CFEWEB\FILIAL2010
rem COPY CFE.EXE C:\CFEWEB\FILIAL2013
COPY CFE.EXE C:\PRJ\20150926
COPY SENHAS.RCB C:\PRJ\20150926
COPY CFE.EXE C:\PRJ\2015M
COPY SENHAS.RCB C:\PRJ\2015M
COPY CFE.EXE C:\PRJ\CFE1506
COPY SENHAS.RCB C:\PRJ\CFE1506

attrib D:\_Sync\Dropbox\Atualizar\cfe.exe -r
copy cfe.exe D:\_Sync\Dropbox\Atualizar
copy cfe.rcb D:\_Sync\Dropbox\Atualizar\cfe.new
